"""g212_trace.py -- every number on research/g212_baseline_verdict.md, asserted
against a stamped book in research/tape/. Exits non-zero on drift.

OMEN 10.0 row R3 (the baseline verdict). The page is prose Austin reads; this
file is the proof underneath it. Nothing here re-types arithmetic:

    research/loop_cycle.py   compute_all / figures / up_to_3_rows -- the SAME
                             functions the loop's gate reads, so the baseline
                             figures on the page are, by construction, the
                             figures the gate will compare every L-row against.
    research/book_stamp.py   book_id -- the fingerprint the OFF arm of every
                             cycle must reproduce; recomputed here from the
                             rows, never trusted from the stamp alone.

THE BASELINE (decided by R3, 2026-09-05; re-affirmed on the refereed R1 pass-4
and R2 pass-3 inputs 2026-09-06):
    trade set   backtest_2y.py at the 2026-09-05 shipped defaults, --days 730,
                built 2026-09-05 at commit 29e4abc6, 499 sessions 2024-09-04 ..
                2026-09-04, ALL 29 archived symbols in the book; the baseline
                SLICE is universe.CORE_SYMBOLS (rows with tier=="core"), the
                settled universe. full29 is reported beside it.
    fill        close -- market at the close of the signal bar
                (entry_fill.ENTRY_FILL default). Phantom column: ENTRY_FILL=
                published, same command, same minute, same commit.
    exit        the shipped engine: 1R hard stop (resting disaster order at
                exactly 1R, fills on an intrabar touch), scale plan
                hod_then_runner_be, account-wide two-loss halt ON.
    unit        up_to_3_stop_win_or_2loss -- his day policy: up to 3 fired-and-
                traded signals a day in arrival order, stop after the first win
                or the second loss. first_of_day and every_signal beside it.
    halves      H1 = sessions before 2025-09-01, H2 = 2025-09-01 onward.
    ceiling     oracle_best_of_day -- the day's best fired-and-traded row,
                chosen after the fact. Proof the setups exist; never a plan.
    rebuild     since L5 flipped signal_runner.DAY_POLICY's default (350b02fc),
                a bare `python backtest_2y.py --days 730` at HEAD builds a
                different book (id 205d3dcee96c5282). The baseline rebuilds
                byte-identically only with DAY_POLICY=first3 in the env --
                loop.json pins it under rebuild.env, and this file asserts the
                pin AND that the stamped book built that way
                (book_DAY_POLICY_off.json.gz, commit 5e8b5b89) carries the
                baseline's own book_id.

Usage:
    python research/g212_trace.py            # assert, exit 1 on drift
    python research/g212_trace.py --print    # dump every computed figure as JSON
"""
from __future__ import annotations

import collections
import gzip
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from research import book_stamp                                      # noqa: E402
from research.loop_cycle import (compute_all, load_book_any,         # noqa: E402
                                 UNIT_FUNCS)

TAPE = ROOT / "research" / "tape"
HONEST = TAPE / "baseline_2026-09-05.json.gz"
PHANTOM = TAPE / "baseline_2026-09-05_published.json.gz"
DAY_POLICY_OFF = TAPE / "book_DAY_POLICY_off.json.gz"   # DAY_POLICY=first3 at 5e8b5b89
DAY_POLICY_ON = TAPE / "book_DAY_POLICY_on.json.gz"     # the engine's own causal picks
LOOP_JSON = TAPE / "loop.json"
BOUNDARY = "2025-09-01"
BASELINE_UNIT = "up_to_3_stop_win_or_2loss"
UNITS = (BASELINE_UNIT, "first_of_day", "every_signal", "oracle_best_of_day")
REBUILD_ENV_PIN = {"DAY_POLICY": "first3"}

# The three books the causal sentence reads (R2's ladder + its referee).
# Unit for all three: every filled signal, $/day = sum(pnl) / distinct trading
# days in the population, 29 symbols, 2024-09-04..2026-09-04, next_open fill.
# fwd_1 / fwd_2 were regenerated by the R2 pass-3 repair (fed8d97f, stamp
# commit 5f8b554e, 2026-09-06 00:43); SIM D is the referee's own book
# (15a729ce, 2026-09-05 18:05). Every cell reproduced to the cent across the
# regeneration (research/r2_referee_pass3.py); only the ids moved.
LADDER_BOOKS = {
    "fwd_1_walk_blind2r": TAPE / "reconcile_fwd_1_add_C_grades.json.gz",
    "simD_engine_blind2r": TAPE / "r2ref_simd_next_open_blind2r_real_engine.json.gz",
    "fwd_2_engine_ladder": TAPE / "reconcile_fwd_2_swap_exit_shipped_ladder.json.gz",
}

# Figures the page quotes from a committed referee report rather than from a
# book in research/tape/ (they need an exit re-walk this file does not own).
# The page names the script; this file asserts the quoted string is still the
# one the committed report prints, so a re-refereed number cannot go stale
# silently. (file, exact substring)
QUOTED_FROM_REPORTS = [
    ("research/r1_referee.md", "| core11 (n=3,479) | +0.0141R [+0.0022, +0.0261] | **+0.0128R [+0.0001, +0.0256]** |"),
    ("research/r1_referee.md", "| full29 (n=7,538) | +0.0140R [+0.0047, +0.0234] | +0.0239R [+0.0136, +0.0341] |"),
    ("research/g210_fill_arms_v2.md", "| core11 | B: intrabar-touch stop (what the engine gives `close`) | $395 22/25 | -$23 8/25 | **$44 12/25** | -$1,457 3/25 | -$46 13/25 | -$720 7/25 |"),
    ("research/g210_fill_arms_v2.md", "| core11 | A: close-only stop (what the five `_walk` arms get) | $479 24/25 | $98 16/25 | **$1,250 22/25** | -$397 10/25 | $1,139 20/25 | $627 20/25 |"),
]


def oracle_rows(rows):
    """The ceiling: each day's best fired-and-traded row (or halted row),
    chosen after the fact. Same candidate pool as the other units."""
    byday = {}
    for r in rows:
        if (r.get("status") == "fired" and r.get("traded")) or r.get("status") == "halted":
            byday.setdefault(r["day"], []).append(r)
    return [max(v, key=lambda r: r.get("pnl", 0.0)) for _, v in sorted(byday.items())]


UNIT_FUNCS["oracle_best_of_day"] = oracle_rows


def core11(rows):
    return [r for r in rows if r.get("tier") == "core"]


# ----------------------------------------------------------------- expected
# Every figure the page prints, keyed exactly like compute_everything()'s
# output. Dollars are whole dollars; R to 4 places. Any drift raises.
_W = lambda **k: k  # noqa: E731  -- a slice dict, keeps the table readable

EXPECTED = {
    "honest": {
        "identity": {"book_id": "2c39ced2697c26cc", "commit": "29e4abc6",
                     "entry_fill": "close", "sessions": 499,
                     "first": "2024-09-04", "last": "2026-09-04",
                     "signals": 127513, "traded": 4053, "halted": 4186,
                     "dirty_engine_py": [],
                     "flags": {"entry_fill.ENTRY_FILL": "close",
                               "loss_halt.LOSS_HALT": True,
                               "stop_rule.DISASTER_STOP_R": 1.0,
                               "backtest_week.DISASTER_STOP": True,
                               "backtest_week.STOP_ON_CLOSE": True,
                               "backtest_week.SCALE_PLAN": "hod_then_runner_be",
                               "signal_runner.RETEST_REQUIRED": True,
                               "signal_runner.RULE84_OFF": False,
                               "signal_runner.ON_WATCH": True}},
        "core11": {
            BASELINE_UNIT: {
                "whole": _W(trades=769, per_day=-52, mean_r=-0.0335, win_pct=45.0,
                            months_green=11, months=25, weeks_green=45, weeks=105,
                            avg_win=801, avg_loss=716, avg_win_over_avg_loss=1.119,
                            fires_per_day=1.541, total_dollars=-25746,
                            worst_drawdown=51106),
                "h1": _W(trades=382, per_day=9, mean_r=0.0057, win_pct=43.7,
                         months_green=6, months=12, avg_win=917, avg_loss=701,
                         avg_win_over_avg_loss=1.308),
                "h2": _W(trades=387, per_day=-111, mean_r=-0.0722, win_pct=46.3,
                         months_green=5, months=13, avg_win=694, avg_loss=732,
                         avg_win_over_avg_loss=0.948)},
            "first_of_day": {
                "whole": _W(trades=498, per_day=-39, mean_r=-0.0392, win_pct=45.7,
                            months_green=9, months=25, avg_win=731, avg_loss=687,
                            avg_win_over_avg_loss=1.064),
                "h1": _W(trades=248, per_day=32, months_green=6, months=12),
                "h2": _W(trades=250, per_day=-109, months_green=3, months=13)},
            "every_signal": {
                "whole": _W(trades=1909, per_day=-132, mean_r=-0.0346, win_pct=46.4,
                            months_green=10, months=25, fires_per_day=3.826,
                            avg_win=770, avg_loss=731),
                "h1": _W(trades=998, per_day=-7, months_green=6, months=12),
                "h2": _W(trades=911, per_day=-257, months_green=4, months=13)},
            "oracle_best_of_day": {
                "whole": _W(trades=498, per_day=1760, mean_r=1.7633, win_pct=95.0,
                            months_green=25, months=25, avg_win=1880, avg_loss=454)}},
        "full29": {
            BASELINE_UNIT: {
                "whole": _W(trades=773, per_day=-9, mean_r=-0.0059, win_pct=45.8,
                            months_green=12, months=25, avg_win=820, avg_loss=703,
                            avg_win_over_avg_loss=1.166),
                "h1": _W(trades=378, per_day=72, months_green=8, months=12),
                "h2": _W(trades=395, per_day=-89, months_green=4, months=13)},
            "first_of_day": {
                "whole": _W(trades=499, per_day=29, mean_r=0.0294, win_pct=45.9,
                            months_green=14, months=25, avg_win=864, avg_loss=678),
                "h1": _W(trades=248, per_day=119, months_green=9, months=12),
                "h2": _W(trades=251, per_day=-60, months_green=5, months=13)},
            "every_signal": {
                "whole": _W(trades=4053, per_day=-334, mean_r=-0.0412, win_pct=44.9,
                            months_green=8, months=25, fires_per_day=8.122,
                            total_dollars=-166871)},
            "oracle_best_of_day": {
                "whole": _W(trades=499, per_day=2681, mean_r=2.6812, win_pct=99.4,
                            months_green=25, months=25)}}},
    "phantom": {
        "identity": {"book_id": "9a629a9682f0676b", "commit": "29e4abc6",
                     "entry_fill": "published", "sessions": 499,
                     "first": "2024-09-04", "last": "2026-09-04",
                     "signals": 134257, "traded": 4230, "halted": 1372,
                     "dirty_engine_py": []},
        "core11": {
            BASELINE_UNIT: {
                "whole": _W(trades=645, per_day=850, mean_r=0.6572, win_pct=63.9,
                            months_green=23, months=25, avg_win=1583, avg_loss=980,
                            avg_win_over_avg_loss=1.615),
                "h1": _W(trades=328, per_day=813, months_green=10, months=12),
                "h2": _W(trades=317, per_day=886, months_green=13, months=13)},
            "first_of_day": {
                "whole": _W(trades=494, per_day=701, mean_r=0.7083, win_pct=67.2,
                            months_green=24, months=25, avg_win=1534, avg_loss=983)},
            "every_signal": {
                "whole": _W(trades=1973, per_day=2328, mean_r=0.5888, win_pct=61.1,
                            months_green=24, months=25)}},
        "full29": {
            BASELINE_UNIT: {
                "whole": _W(trades=668, per_day=929, mean_r=0.6942, win_pct=64.2,
                            months_green=25, months=25, avg_win=1625, avg_loss=977)},
            "first_of_day": {
                "whole": _W(trades=498, per_day=683, months_green=24, months=25)},
            "every_signal": {
                "whole": _W(trades=4230, per_day=5167, mean_r=0.6096, win_pct=59.9,
                            months_green=25, months=25, total_dollars=2578552,
                            avg_win=1672, avg_loss=977)}}},
    # The engine's own causal day-policy picks (day_policy.py walks entries in
    # order and only credits a stop once the trade has CLOSED), read off the
    # L5 ON book: core-11 rows with status=="fired" and traded. Reported
    # beside the gate unit, never the gate. $/day over the 499 sessions.
    "causal_day_policy": {
        "identity": {"book_id": "205d3dcee96c5282", "commit": "5e8b5b89",
                     "day_policy": "3fires_stop_win_or_2loss"},
        "whole": _W(trades=814, per_day=-4, months_green=12, months=25,
                    win_pct=47.3, avg_win=761, avg_loss=693, halted_by_policy=1095),
        "h1": _W(trades=432, per_day=41, months_green=7, months=12),
        "h2": _W(trades=382, per_day=-45, months_green=5, months=13),
    },
    "rebuild": {
        # A book built with the pin at a later commit carries the baseline's id.
        "day_policy_off": {"book_id": "2c39ced2697c26cc", "commit": "5e8b5b89",
                           "day_policy": "first3"},
        "bare_head_default": {"book_id": "205d3dcee96c5282"},
    },
    "ladder": {
        "fwd_1_walk_blind2r": _W(trades=14327, days=499, per_day=4569.49, mean_r=0.1592,
                                 win_pct_all=38.8, wins=5556, losses=8771, scratches=0,
                                 avg_win_r=1.9835, avg_loss_r=-0.9965,
                                 book_id="d3b7151c374a9f7f", commit="5f8b554e"),
        "simD_engine_blind2r": _W(trades=14332, days=499, per_day=149.80, mean_r=0.0052,
                                  win_pct_all=33.6, wins=4820, losses=9512, scratches=0,
                                  avg_win_r=1.9837, avg_loss_r=-0.9973,
                                  book_id="6b3b862ce4ffebe0", commit="15a729ce"),
        "fwd_2_engine_ladder": _W(trades=14332, days=499, per_day=-980.93, mean_r=-0.0342,
                                  win_pct_all=42.7, wins=6117, losses=8175, scratches=40,
                                  avg_win_r=1.0312, avg_loss_r=-0.8315,
                                  book_id="a2ff837493e9a7d2", commit="5f8b554e"),
        "legs": _W(whole_step=-5550.42, substrate_leg=-4419.69, ladder_leg=-1130.73,
                   substrate_share_pct=79.6),
    },
}

TOL = {"trades": 0, "per_day": 1, "mean_r": 0.001, "months_green": 0, "months": 0,
       "weeks_green": 0, "weeks": 0, "win_pct": 0.1, "win_pct_all": 0.1,
       "avg_win": 1, "avg_loss": 1, "avg_win_r": 0.001, "avg_loss_r": 0.001,
       "avg_win_over_avg_loss": 0.01, "total_dollars": 1, "worst_drawdown": 1,
       "fires_per_day": 0.001, "days_traded": 0, "days": 0,
       "wins": 0, "losses": 0, "scratches": 0, "halted_by_policy": 0,
       "whole_step": 0.01, "substrate_leg": 0.01, "ladder_leg": 0.01,
       "substrate_share_pct": 0.1}


def _stamp_bits(meta):
    st = meta.get("stamp", {}) or {}
    git = st.get("git", {}) or {}
    flags = st.get("flags", {}) or {}
    return st, git, flags


def book_figures(path):
    meta, rows = load_book_any(path)
    st, git, flags = _stamp_bits(meta)
    out = {"identity": {"book_id": st.get("book_id"),
                        "commit": (git.get("commit") or "")[:8],
                        "dirty_engine_py": git.get("dirty_engine_py"),
                        "dirty_py_count": git.get("dirty_py_count"),
                        "built_at": st.get("built_at"),
                        "entry_fill": meta.get("entry_fill"),
                        "sessions": meta.get("sessions"),
                        "first": meta.get("first"), "last": meta.get("last"),
                        "signals": meta.get("signals"), "traded": meta.get("traded"),
                        "halted": meta.get("halted"),
                        "flags": {k: v for k, v in flags.items()
                                  if k.split(".")[-1] in (
                                      "ENTRY_FILL", "SCALE_PLAN", "DISASTER_STOP",
                                      "STOP_ON_CLOSE", "PESSIMISTIC_FILL", "LOSS_HALT",
                                      "RETEST_REQUIRED", "DEDUPE_MODE", "LADDER_WEIGHTS",
                                      "DISASTER_STOP_R", "RULE84_OFF", "ON_WATCH")}},
           "core11": {}, "full29": {}}
    recomputed = book_stamp.book_id(rows)
    if recomputed != st.get("book_id"):
        raise SystemExit("%s: stamp book_id %s != recomputed %s"
                         % (path.name, st.get("book_id"), recomputed))
    for uni_name, uni_rows in (("core11", core11(rows)), ("full29", rows)):
        for unit in UNITS:
            out[uni_name][unit] = compute_all(meta, uni_rows, unit, BOUNDARY)
    return out


def _slice(rows, all_months, sessions):
    days = {r["day"] for r in rows}
    tot = sum(r["pnl"] for r in rows)
    by_m = collections.defaultdict(float)
    for r in rows:
        by_m[r["day"][:7]] += r["pnl"]
    w = [r["pnl"] for r in rows if r["pnl"] > 0]
    l = [r["pnl"] for r in rows if r["pnl"] < 0]
    return {"trades": len(rows), "days_traded": len(days),
            "per_day": round(tot / sessions),
            "months_green": sum(1 for m in all_months if by_m.get(m, 0.0) > 0),
            "months": len(all_months),
            "win_pct": round(100.0 * len(w) / len(rows), 1) if rows else None,
            "avg_win": round(sum(w) / len(w)) if w else None,
            "avg_loss": round(-sum(l) / len(l)) if l else None}


def causal_figures():
    """The engine-side day policy (day_policy.py, L5) on its own ON book."""
    meta, rows = load_book_any(DAY_POLICY_ON)
    st, git, flags = _stamp_bits(meta)
    if book_stamp.book_id(rows) != st.get("book_id"):
        raise SystemExit("%s: stamp book_id != recomputed" % DAY_POLICY_ON.name)
    core = core11(rows)
    picks = [r for r in core if r.get("status") == "fired" and r.get("traded")]
    sessions = meta.get("sessions")
    all_m = sorted({r["day"][:7] for r in core})
    h1 = [r for r in picks if r["day"] < BOUNDARY]
    h2 = [r for r in picks if r["day"] >= BOUNDARY]
    out = {"identity": {"book_id": st.get("book_id"),
                        "commit": (git.get("commit") or "")[:8],
                        "day_policy": flags.get("signal_runner.DAY_POLICY")},
           "whole": _slice(picks, all_m, sessions),
           "h1": _slice(h1, [m for m in all_m if m < BOUNDARY[:7]], sessions),
           "h2": _slice(h2, [m for m in all_m if m >= BOUNDARY[:7]], sessions)}
    out["whole"]["halted_by_policy"] = sum(1 for r in core if r.get("status") == "day_policy_halt")
    return out


def rebuild_figures():
    """Proof the pinned rebuild reproduces the baseline id at a later commit."""
    out = {}
    meta, rows = load_book_any(DAY_POLICY_OFF)
    st, git, flags = _stamp_bits(meta)
    out["day_policy_off"] = {"book_id": book_stamp.book_id(rows),
                             "commit": (git.get("commit") or "")[:8],
                             "day_policy": flags.get("signal_runner.DAY_POLICY")}
    meta, rows = load_book_any(DAY_POLICY_ON)
    out["bare_head_default"] = {"book_id": book_stamp.book_id(rows)}
    return out


def ladder_figures():
    out = {}
    for name, path in LADDER_BOOKS.items():
        with gzip.open(path, "rt", encoding="utf-8") as f:
            b = json.load(f)
        rows = [r for r in b["trades"] if r.get("filled", True)
                and r.get("pnl") is not None and r.get("r") is not None]
        days = len({r["day"] for r in rows})
        tot = sum(r["pnl"] for r in rows)
        wins = sum(1 for r in rows if r["pnl"] > 0)
        losses = sum(1 for r in rows if r["pnl"] < 0)
        w = [r["r"] for r in rows if r["pnl"] > 0]
        l = [r["r"] for r in rows if r["pnl"] < 0]
        st = b["meta"]["stamp"]
        out[name] = {"trades": len(rows), "days": days,
                     "per_day": round(tot / days, 2),
                     "mean_r": round(sum(r["r"] for r in rows) / len(rows), 4),
                     "win_pct_all": round(100.0 * wins / len(rows), 1),
                     "wins": wins, "losses": losses,
                     "scratches": len(rows) - wins - losses,
                     "avg_win_r": round(sum(w) / len(w), 4) if w else None,
                     "avg_loss_r": round(sum(l) / len(l), 4) if l else None,
                     "book_id": st["book_id"],
                     "commit": ((st.get("git") or {}).get("commit") or "")[:8],
                     "built_at": st.get("built_at"),
                     "exit_plan": b["meta"].get("exit_plan"),
                     "fill": b["meta"].get("fill")}
    a, d, c = (out["fwd_1_walk_blind2r"], out["simD_engine_blind2r"],
               out["fwd_2_engine_ladder"])
    legs = {"whole_step": round(c["per_day"] - a["per_day"], 2),
            "substrate_leg": round(d["per_day"] - a["per_day"], 2),
            "ladder_leg": round(c["per_day"] - d["per_day"], 2)}
    legs["substrate_share_pct"] = round(100.0 * legs["substrate_leg"] / legs["whole_step"], 1)
    out["legs"] = legs
    return out


def compute_everything():
    return {"honest": book_figures(HONEST), "phantom": book_figures(PHANTOM),
            "causal_day_policy": causal_figures(),
            "rebuild": rebuild_figures(),
            "ladder": ladder_figures()}


# ------------------------------------------------------------------- assert

def _walk(exp, got, path, bad):
    if isinstance(exp, dict):
        if not isinstance(got, dict):
            bad.append("%s: expected a table, book gives %r" % (path, got))
            return
        for k, v in exp.items():
            if k not in got:
                bad.append("%s.%s: missing in computed figures" % (path, k))
                continue
            _walk(v, got[k], "%s.%s" % (path, k), bad)
        return
    field = path.split(".")[-1]
    tol = TOL.get(field, 0)
    if (isinstance(exp, (int, float)) and isinstance(got, (int, float))
            and not isinstance(exp, bool) and not isinstance(got, bool)):
        if abs(exp - got) > tol:
            bad.append("%s: page says %s, book gives %s (tol %s)" % (path, exp, got, tol))
    elif exp != got:
        bad.append("%s: page says %r, book gives %r" % (path, exp, got))


def _leaves(d):
    if isinstance(d, dict):
        for v in d.values():
            yield from _leaves(v)
    else:
        yield d


def main():
    if "--print" in sys.argv:
        print(json.dumps(compute_everything(), indent=1, default=str))
        return 0
    got = compute_everything()
    bad = []
    _walk(EXPECTED, got, "g212", bad)

    # the two fills are the same command on the same sessions, same day, same commit
    hi, pi = got["honest"]["identity"], got["phantom"]["identity"]
    for k in ("sessions", "first", "last", "commit"):
        if hi[k] != pi[k]:
            bad.append("honest vs phantom %s: %r vs %r" % (k, hi[k], pi[k]))
    if (hi["built_at"] or "")[:10] != (pi["built_at"] or "")[:10]:
        bad.append("honest vs phantom built on different days: %s vs %s"
                   % (hi["built_at"], pi["built_at"]))

    # the pinned rebuild reproduces the baseline; the bare HEAD default does not
    rb = got["rebuild"]
    if rb["day_policy_off"]["book_id"] != hi["book_id"]:
        bad.append("book_DAY_POLICY_off (DAY_POLICY=first3) id %s != baseline %s"
                   % (rb["day_policy_off"]["book_id"], hi["book_id"]))
    if rb["bare_head_default"]["book_id"] == hi["book_id"]:
        bad.append("book_DAY_POLICY_on id equals the baseline -- the pin note on the page is stale")

    # figures quoted from committed referee reports (need an exit re-walk this
    # file does not own): the exact string must still be what the report prints
    for rel, needle in QUOTED_FROM_REPORTS:
        p = ROOT / rel
        if not p.exists():
            bad.append("%s missing (page quotes it)" % rel)
        elif needle not in p.read_text(encoding="utf-8"):
            bad.append("%s no longer contains the quoted row: %s" % (rel, needle[:60]))

    # loop.json must point at this book, this unit, this boundary, this id, this pin
    if LOOP_JSON.exists():
        cfg = json.loads(LOOP_JSON.read_text(encoding="utf-8"))
        if Path(cfg.get("baseline_book", "")).name != HONEST.name:
            bad.append("loop.json baseline_book %r is not %s" % (cfg.get("baseline_book"), HONEST.name))
        if cfg.get("unit") != BASELINE_UNIT:
            bad.append("loop.json unit %r is not %s" % (cfg.get("unit"), BASELINE_UNIT))
        if cfg.get("halves_boundary") != BOUNDARY:
            bad.append("loop.json halves_boundary %r != %s" % (cfg.get("halves_boundary"), BOUNDARY))
        if cfg.get("baseline_book_id") != hi["book_id"]:
            bad.append("loop.json baseline_book_id %r != stamped %s"
                       % (cfg.get("baseline_book_id"), hi["book_id"]))
        rebuild = cfg.get("rebuild", {})
        for k, v in REBUILD_ENV_PIN.items():
            if rebuild.get("env", {}).get(k) != v:
                bad.append("loop.json rebuild.env.%s is %r, must be %r -- without the pin the "
                           "OFF arm builds %s, not the baseline"
                           % (k, rebuild.get("env", {}).get(k), v,
                              rb["bare_head_default"]["book_id"]))
        if list(rebuild.get("args", [])) != ["--days", "730"] or rebuild.get("script") != "backtest_2y.py":
            bad.append("loop.json rebuild.script/args drifted: %r %r"
                       % (rebuild.get("script"), rebuild.get("args")))
        uni = cfg.get("universe", {})
        if uni.get("row_filter") != 'tier == "core"':
            bad.append("loop.json universe.row_filter %r != 'tier == \"core\"'" % uni.get("row_filter"))
        bf = cfg.get("baseline_figures", {})
        base = got["honest"]["core11"][BASELINE_UNIT]
        for sl in ("whole", "h1", "h2"):
            for fld in ("per_day", "months_green", "months", "trades"):
                if bf.get(sl, {}).get(fld) != base[sl].get(fld):
                    bad.append("loop.json baseline_figures.%s.%s %r != book %r"
                               % (sl, fld, bf.get(sl, {}).get(fld), base[sl].get(fld)))
    else:
        bad.append("research/tape/loop.json missing")

    if bad:
        print("FAIL -- %d figure(s) on research/g212_baseline_verdict.md no longer trace:" % len(bad))
        for b in bad:
            print("  " + b)
        return 1
    n = sum(1 for _ in _leaves(EXPECTED)) + len(QUOTED_FROM_REPORTS)
    print("PASS -- %d figures on research/g212_baseline_verdict.md trace to %s (id %s), "
          "%s (id %s), the L5 pair, the three ladder books and two committed referee reports"
          % (n, HONEST.name, hi["book_id"], PHANTOM.name, pi["book_id"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
