"""P21 / W7 -- is there a 2R target at entry, and does it separate winners
from losers?

G7 (`research/g7_exit_sweep.md`) and P10 (`research/p10_structure_trail.md`)
both closed on the same sentence: "the exit is not the binding constraint;
the constraint is information at entry." P10 measured the ceiling -- a
stop-respecting hindsight oracle returns +3.501R inside the 11:00 window and
the incumbent captures 27.3% of it, and the 473 losing signals average
+0.647R of oracle -- so price alone cannot separate winners from losers.

Austin, rule ballot batch 02 row b4 (`research/rule_ballot_batch02.jsonl`):

    "its about sizing for the mean 2rr, so if there are no other levels to
    target, or its not an s trade to begin with, harder to trade."

This is the first candidate for the entry-side information G7/G9 pointed at.
The question, stated exactly: at the moment of entry, with the stop already
known, is there a level the engine actually tracks that sits AT OR BEYOND
entry +/- 2R in the trade's direction? If not, no exit policy can pay the
2.0R money gate on that trade -- there is nowhere for the price to have gone.

THE LEVEL ROSTER (named, so the claim is checkable against the code that
computes it in production):

  * PDH / PDL   -- previous trading day's RTH high/low.
                   `backtest_2y.py::daily_ohlc` (high, low columns).
  * PMH / PML   -- premarket high/low for the session.
                   `polygon_feed.py::premarket_hi_lo`.
  * OR high/low -- first 5 RTH bars' high/low (the opening range).
                   `backtest_week.py`'s own `orh`/`orl` (`candles[:5]`).
  * HOD / LOD   -- the session extreme AS OF THE ENTRY BAR (inclusive),
                   causal -- exactly `backtest_week.py`'s `scale_level`
                   (`max(c.high for c in candles[:i+1])`).
  * T10 pivots  -- swing highs/lows, `signal_runner.py::pivot_levels` with
                   the engine's own defaults (`PIVOT_STRENGTH=2`,
                   `PIVOT_LOOKBACK=30`), called with `as_of=entry_i` so no
                   pivot that had not yet formed (needs `strength` bars to
                   its right) is used -- the same no-lookahead guarantee the
                   live mesh check (`signal_runner.blocking_levels`,
                   T11(c)) relies on.

This is the SAME roster `signal_runner.py` already assembles as
`self._active_levels + self._pivot_prices` for the "in-between mesh" veto
(a level sitting BETWEEN entry and 2R blocks the trade). This script asks
the mirror-image question: is there a level AT OR BEYOND 2R, i.e. is there
anywhere to point the trade at, at all.

METHODOLOGY NOTE. "Reachable before 11:00" in the work item is read as: the
level must be one the engine could already name at entry (computed only from
bars <= entry_i, or from static prior-session data) -- NOT that price must
actually have traded there. Requiring an actual touch would fold the trade's
own outcome into the feature and the flag would stop being an entry-time
signal. Every level here is causal by construction (see roster above).

CAUSALITY. PDH/PDL/PMH/PML are fixed before the session opens. OR high/low
locks after bar 5 (09:34) and every signal in the traded book enters at or
after that. HOD/LOD-to-date and the pivot roster are built only from bars
`<= entry_i`, matching `backtest_week.py::simulate_day`'s own `scale_level`
and `signal_runner.py`'s own `pivot_levels(..., as_of=entry_i)`.

REPORT ONLY. No gate, no routing change. `research/p21_target_availability.md`
is generated by this script; no number in it should be quoted without it.

Usage:
    python research/p21_target_availability.py [--inp ...] [--out ...]
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import polygon_feed as pf                                   # noqa: E402
import backtest_2y as bt2y                                   # noqa: E402
from signal_runner import pivot_levels, PIVOT_LOOKBACK        # noqa: E402

_full_cache = {}     # sym -> {day: [Candle, ...]} full-session bars (incl. premarket)
_rth_cache = {}      # sym -> {day: [Candle, ...]} RTH-only bars
_ohlc_cache = {}      # sym -> {day: (open, close, high, low)} from bt2y.daily_ohlc
_days_cache = {}      # sym -> sorted list of archived days


def _full_bars(sym, day):
    d = _full_cache.setdefault(sym, {})
    if day not in d:
        try:
            d[day] = pf.fetch_day(sym, day)
        except Exception:
            d[day] = []
    return d[day]


def _rth_bars(sym, day):
    d = _rth_cache.setdefault(sym, {})
    if day not in d:
        d[day] = pf.rth(_full_bars(sym, day))
    return d[day]


def entry_index(sym, day, et):
    """Index into `_rth_bars(sym, day)` of the bar whose timestamp matches
    `et` ("HH:MM"). `research/bt2y_trades.json` does not carry `entry_i`
    itself (that field was added to `backtest_2y.py` after this book was
    generated) -- recovered the same way `research/p10_structure_trail.py`
    ::load_book does: match the entry-time string against the RTH bars."""
    rth = _rth_bars(sym, day)
    for i, c in enumerate(rth):
        if c.timestamp[:5] == et:
            return i
    return None


def _prev_day(sym, day):
    days = _days_cache.get(sym)
    if days is None:
        days = _days_cache[sym] = bt2y.archive_days(sym)
    try:
        i = days.index(day)
    except ValueError:
        return None
    return days[i - 1] if i > 0 else None


def _pdh_pdl(sym, day):
    prev = _prev_day(sym, day)
    if prev is None:
        return None, None
    ohlc = _ohlc_cache.get(sym)
    if ohlc is None:
        ohlc = _ohlc_cache[sym] = bt2y.daily_ohlc(sym)
    row = ohlc.get(prev)
    if row is None:
        return None, None
    _open, _close, high, low = row
    return high, low


def levels_for_entry(sym, day, entry_i):
    """The named roster, as of the entry bar. Returns {name: price}, prices
    for missing/unavailable levels omitted (never a fake 0.0 or None kept in
    the dict)."""
    rth = _rth_bars(sym, day)
    if not rth or entry_i is None or entry_i >= len(rth):
        return {}
    out = {}
    pdh, pdl = _pdh_pdl(sym, day)
    if pdh is not None:
        out["PDH"] = pdh
    if pdl is not None:
        out["PDL"] = pdl
    pmh, pml = pf.premarket_hi_lo(_full_bars(sym, day))
    if pmh is not None:
        out["PMH"] = pmh
    if pml is not None:
        out["PML"] = pml
    if len(rth) >= 5:
        out["ORH"] = max(c.high for c in rth[:5])
        out["ORL"] = min(c.low for c in rth[:5])
    out["HOD"] = max(c.high for c in rth[:entry_i + 1])
    out["LOD"] = min(c.low for c in rth[:entry_i + 1])
    for p in pivot_levels(rth, as_of=entry_i, lookback=PIVOT_LOOKBACK):
        out[p["name"]] = p["price"]
    return out


def has_2r_target(levels, entry, stop, direction):
    """Is any tracked level at or beyond entry +/- 2R in the trade's
    direction? Returns (bool, best_level_name_or_None, best_price_or_None) --
    the nearest qualifying level beyond the gate, for spot-checking."""
    risk = abs(entry - stop)
    if risk <= 0 or not levels:
        return False, None, None
    long = direction == "call"
    target = entry + 2 * risk if long else entry - 2 * risk
    qualifying = [(name, px) for name, px in levels.items()
                  if (px >= target if long else px <= target)]
    if not qualifying:
        return False, None, None
    # nearest to the 2R line (least excess reach), not the farthest
    best = min(qualifying, key=lambda kv: abs(kv[1] - target))
    return True, best[0], best[1]


def agg(rs):
    """(n, win%, mean R, total R). Wins are R > 0; scratches (R == 0) are
    excluded from the win-rate denominator. Same convention as
    `research/p10_structure_trail.py::agg` / `g7_exit_sweep.agg`."""
    rs = [r for r in rs if r is not None]
    if not rs:
        return 0, 0.0, 0.0, 0.0
    w = sum(1 for r in rs if r > 0)
    dec = sum(1 for r in rs if r != 0)
    return len(rs), (w / dec * 100 if dec else 0.0), sum(rs) / len(rs), sum(rs)


def table(rows, cols):
    out = ["| slice | " + " | ".join(cols) + " |",
           "|---" * (len(cols) + 1) + "|"]
    for label, cells in rows:
        out.append("| " + label + " | " + " | ".join(cells) + " |")
    return out


def split_block(title, book, flags):
    """flags[i] is True/False/None (None = level data unavailable). Pass
    title=None to omit the heading (caller supplies its own)."""
    cols = ["n", "win%", "mean R", "median R", "total R"]
    rows = []
    for label, want in (("has 2R target", True), ("no 2R target", False)):
        idx = [i for i, f in enumerate(flags) if f is want]
        rs = sorted(book[i]["r"] for i in idx)
        n, wr, mr, tr = agg(rs)
        med = rs[len(rs) // 2] if rs else 0.0
        rows.append((label, ["%d" % n, "%.1f" % wr, "%+.3f" % mr,
                             "%+.3f" % med, "%+.1f" % tr]))
    unk = sum(1 for f in flags if f is None)
    lines = [] if title is None else ["", "### " + title, ""]
    if unk:
        lines.append("(%d/%d signals had no level data -- symbol/day archive "
                     "gap or too few RTH bars -- excluded from both rows "
                     "below)" % (unk, len(flags)))
        lines.append("")
    lines += table(rows, cols)
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--inp", default="research/bt2y_trades.json")
    ap.add_argument("--out", default="research/p21_target_availability.md")
    args = ap.parse_args()

    raw = json.loads((ROOT / args.inp).read_text(encoding="utf-8"))
    meta = raw["meta"]
    book = [t for t in raw["trades"] if t["traded"]]
    print("%d traded signals, %s..%s" % (len(book), meta["first"], meta["last"]))

    flags = []
    examples = []
    for n, t in enumerate(book, 1):
        entry_i = t["entry_i"] if "entry_i" in t else entry_index(t["sym"], t["day"], t["et"])
        levels = levels_for_entry(t["sym"], t["day"], entry_i)
        if not levels:
            flags.append(None)
        else:
            flag, name, px = has_2r_target(levels, t["entry"], t["stop"], t["dir"])
            flags.append(flag)
            if len(examples) < 5:
                examples.append((t["sym"], t["day"], t["dir"], t["entry"],
                                 t["stop"], flag, name, px))
        if n % 250 == 0:
            print("  %d/%d" % (n, len(book)))

    n_book = len(book)
    n_has = sum(1 for f in flags if f is True)
    n_no = sum(1 for f in flags if f is False)
    n_unk = sum(1 for f in flags if f is None)
    print("has_2r_target: %d yes, %d no, %d unknown (of %d)"
          % (n_has, n_no, n_unk, n_book))

    lose_idx = [i for i, t in enumerate(book) if t["r"] <= 0]
    win_idx = [i for i, t in enumerate(book) if t["r"] > 0]
    lose_no_target = sum(1 for i in lose_idx if flags[i] is False)
    lose_has_target = sum(1 for i in lose_idx if flags[i] is True)
    lose_unk = sum(1 for i in lose_idx if flags[i] is None)
    win_no_target = sum(1 for i in win_idx if flags[i] is False)
    win_has_target = sum(1 for i in win_idx if flags[i] is True)
    win_unk = sum(1 for i in win_idx if flags[i] is None)

    s_idx = [i for i, t in enumerate(book) if t.get("sgrade") == "S"]
    s_book = [book[i] for i in s_idx]
    s_flags = [flags[i] for i in s_idx]
    s_all_n, s_all_wr, s_all_mr, s_all_tr = agg([t["r"] for t in s_book])

    lines = ["# P21 (W7) -- is there a 2R target at entry?", "",
             "Generated by `research/p21_target_availability.py` over **%d** "
             "traded signals (%s -> %s) from `%s`. Report only -- no gate, no "
             "routing change." % (n_book, meta["first"], meta["last"], args.inp),
             "",
             "Austin, rule ballot batch 02 row b4 (`research/rule_ballot_batch02"
             ".jsonl`): *\"its about sizing for the mean 2rr, so if there are no "
             "other levels to target, or its not an s trade to begin with, "
             "harder to trade.\"* G7 and P10 both closed on \"the constraint is "
             "information at entry\" -- this is the first candidate for that "
             "information.", "",
             "## The level roster", "",
             "The same roster `signal_runner.py` already assembles for the "
             "in-between-mesh veto (T11(c), `blocking_levels`) -- this script "
             "asks the mirror question, whether a level sits AT OR BEYOND 2R "
             "rather than between entry and it.", "",
             "| level | source |",
             "|---|---|",
             "| PDH / PDL | previous trading day's RTH high/low "
             "(`backtest_2y.py::daily_ohlc`) |",
             "| PMH / PML | premarket high/low for the session "
             "(`polygon_feed.py::premarket_hi_lo`) |",
             "| OR high/low | first 5 RTH bars' high/low "
             "(`backtest_week.py`'s `orh`/`orl`) |",
             "| HOD / LOD | session extreme as of the entry bar, causal "
             "(`backtest_week.py`'s `scale_level`) |",
             "| T10 pivots | swing highs/lows, `signal_runner.py::pivot_levels`"
             ", `PIVOT_STRENGTH=2`, `PIVOT_LOOKBACK=30`, `as_of=entry_i` |",
             "",
             "`has_2r_target` = at least one of the above sits at or beyond "
             "`entry +/- 2R` (long/short) as of the entry bar. %d/%d signals "
             "had no usable level data (archive gap or <5 RTH bars) and are "
             "reported as a separate row, never folded into either side."
             % (n_unk, n_book), ""]

    lines += split_block("Whole book, has 2R target vs. not", book, flags)
    lines += ["", "### Austin grade S only (n=%d, incumbent %+.3fR)"
              % (s_all_n, s_all_mr), ""]
    lines += split_block(None, s_book, s_flags)

    lines += ["", "## The 473-loser / winner split", "",
              "Of the book's losing signals (R <= 0, n=%d) and winning "
              "signals (R > 0, n=%d):" % (len(lose_idx), len(win_idx)), "",
              "| | no 2R target | has 2R target | unknown |",
              "|---|---|---|---|",
              "| losers (n=%d) | %d (%.1f%%) | %d (%.1f%%) | %d |"
              % (len(lose_idx), lose_no_target,
                 lose_no_target / len(lose_idx) * 100 if lose_idx else 0.0,
                 lose_has_target,
                 lose_has_target / len(lose_idx) * 100 if lose_idx else 0.0,
                 lose_unk),
              "| winners (n=%d) | %d (%.1f%%) | %d (%.1f%%) | %d |"
              % (len(win_idx), win_no_target,
                 win_no_target / len(win_idx) * 100 if win_idx else 0.0,
                 win_has_target,
                 win_has_target / len(win_idx) * 100 if win_idx else 0.0,
                 win_unk),
              ""]

    # The verdict. Austin's hypothesis has a DIRECTION: losers should lack a
    # 2R target MORE OFTEN than winners (no room to reach the gate -> loses).
    # `gap` alone cannot tell a confirmation from an inversion -- it has to be
    # signed and read against that direction, not just thresholded.
    no_rate_lose = (lose_no_target / len(lose_idx) * 100) if lose_idx else 0.0
    no_rate_win = (win_no_target / len(win_idx) * 100) if win_idx else 0.0
    signed_gap = no_rate_lose - no_rate_win   # > 0 supports the hypothesis
    has_mean = agg([book[i]["r"] for i in range(n_book) if flags[i] is True])[2]
    no_mean = agg([book[i]["r"] for i in range(n_book) if flags[i] is False])[2]
    has_wr = agg([book[i]["r"] for i in range(n_book) if flags[i] is True])[1]
    no_wr = agg([book[i]["r"] for i in range(n_book) if flags[i] is False])[1]
    if signed_gap >= 10.0:
        verdict = ("**The flag separates them, in the predicted direction.** "
                   "%.1f%% of losers had no 2R target at entry against only "
                   "%.1f%% of winners (a %.1f-point gap the right way round) "
                   "-- this is real entry-side information."
                   % (no_rate_lose, no_rate_win, signed_gap))
    elif signed_gap <= -10.0:
        verdict = ("**The flag runs BACKWARDS from the hypothesis -- stated "
                   "plainly, not dressed up.** Austin's rule predicts losers "
                   "should lack a 2R target more often than winners. The "
                   "book says the opposite: only %.1f%% of losers had no "
                   "target at entry, against %.1f%% of winners (a %.1f-point "
                   "gap the WRONG way round). No-target trades actually win "
                   "*more* often (%.1f%% vs %.1f%%) though for less when "
                   "they do (mean %+.3fR vs %+.3fR with a target) -- reading "
                   "consistent with 'no overhead level = open air, price "
                   "runs clean to a modest target'; a real level beyond 2R "
                   "looks like room but is also something for price to stall "
                   "or reject at. **This is a negative result for the flag "
                   "as specified**: it does not identify which of the 473 "
                   "losers were unwinnable at entry, and by this measure a "
                   "present target is if anything the worse sign, not the "
                   "better one."
                   % (no_rate_lose, no_rate_win, -signed_gap, no_wr, has_wr,
                      no_mean, has_mean))
    else:
        verdict = ("**The flag does not separate them.** Losers were missing "
                   "a 2R target %.1f%% of the time against %.1f%% for winners "
                   "-- a %.1f-point gap, too small to call a relationship "
                   "either way. Whole-book mean R is %+.3fR with a target "
                   "vs. %+.3fR without. Stated plainly: this is a negative "
                   "result." % (no_rate_lose, no_rate_win, abs(signed_gap),
                                has_mean, no_mean))
    lines += ["## Verdict", "", verdict, ""]

    (ROOT / args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", args.out)


if __name__ == "__main__":
    main()
