"""t66 -- what would the downgrade grader actually do?

`research/downgrade.py` implements Austin's S/A/C arithmetic. This measures it
against his 120 graded day-cards WITHOUT wiring it into the engine, because 5.2
published a table nobody could reproduce and the lesson was: measure first.

The engine's own detection is left exactly as it is. Every signal it produces is
re-graded by `downgrade.score()`, and the two questions are:

    recall      how many of his 28 S-days would fire, if the engine traded the
                grades the new grader hands out
    false fires how many of the 61 days he refused would fire too

Those move together and there is no credit banked -- head-to-head came back 0/9,
so every current false fire is a real one. Reporting either alone is misleading.

    python research/t66_downgrade_measure.py

Writes research/t66_downgrade_measure.md.
"""
from __future__ import annotations

import os
import sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)

from research import downgrade as dg                                   # noqa: E402
from research.t4_engine_recall import (CaptureRunner, rth_candles, prior_day_levels,
                                       premarket_extremes, htf_bias, ENTRY_CUTOFF)
from research.t60_baseline import load_day_cards                       # noqa: E402

OUT = os.path.join(HERE, "t66_downgrade_measure.md")
TOL = 3
OLD_SKIP = ("X", "D")
# Austin, 2026-08-24, asked directly: "S only". His reason, from the rule ballot:
# "S trades are the most important because it's what actual money will go to."
TRADEABLE = ("S",)


def as_dicts(candles):
    return [{"o": c.open, "h": c.high, "l": c.low, "c": c.close, "v": c.volume}
            for c in candles]


def replay(symbol, day):
    candles = rth_candles(symbol, day)
    if not candles:
        return None, None
    pdh, pdl, pdo, pdc = prior_day_levels(symbol, day)
    pmh, pml = premarket_extremes(symbol, day)
    r = CaptureRunner(symbol)
    r.pdh, r.pdl = pdh, pdl
    r.pmh, r.pml = pmh, pml
    r.pd_open, r.pd_close = pdo, pdc
    bias = htf_bias(symbol, day)
    r.htf_bias = bias
    r.qqq_breaks = None

    out = []
    for i in range(5, len(candles)):
        if ENTRY_CUTOFF and candles[i].timestamp >= ENTRY_CUTOFF:
            continue
        r.candles = candles[: i + 1]
        before = len(r.captured)
        try:
            r.detect_signals()
        except Exception:
            continue
        for s in r.captured[before:]:
            out.append({"bar": i, "old": s.get("grade"), "stop": s.get("stop"),
                        "dir": s.get("direction"), "bias": bias})
    return out, as_dicts(candles)


def main():
    days, marks = load_day_cards()
    by_day = defaultdict(list)
    for m in marks:
        if m.get("entry_i") is not None:
            by_day[(m["symbol"], m["date"])].append(m)

    new_grades = Counter()
    tripped_counts = Counter()
    tp_new = Counter()
    tp_old = Counter()
    confluence_hits = 0
    day_fire_old, day_fire_new = set(), set()
    n_sigs = n_tp = 0
    days_run = 0

    for (sym, date) in sorted(days):
        sigs, bars = replay(sym, date)
        if sigs is None:
            continue
        days_run += 1
        mine = by_day.get((sym, date), [])
        for s in sigs:
            n_sigs += 1
            if s["old"] not in OLD_SKIP:
                day_fire_old.add((sym, date))
            rec = dg.score(bars, s["bar"], s["stop"], s["dir"] == "call",
                           htf_bias=s["bias"])
            if rec is None:
                continue
            new_grades[rec["grade"]] += 1
            tripped_counts[rec["n_tripped"]] += 1
            confluence_hits += 1 if rec["confluence"] else 0
            if rec["grade"] in TRADEABLE:
                day_fire_new.add((sym, date))
            if any(abs(s["bar"] - m["entry_i"]) <= TOL for m in mine):
                n_tp += 1
                tp_new[rec["grade"]] += 1
                tp_old[s["old"]] += 1

    graded = {k: (v.get("grade") or "").strip() for k, v in days.items()}
    s_days = {k for k, g in graded.items() if g == "S"}
    trade_days = {k for k, g in graded.items() if g not in ("", "none")}
    none_days = {k for k, g in graded.items() if g == "none"}

    def pct(a, b):
        return 100.0 * a / max(b, 1)

    rows = []
    for label, fired in (("engine today", day_fire_old), ("downgrade grader", day_fire_new)):
        rows.append((label,
                     len(fired & s_days), len(s_days),
                     len(fired & trade_days), len(trade_days),
                     len(fired & none_days), len(none_days)))

    L = ["# T66 — what the downgrade grader would do", ""]
    L.append("Generated by `research/t66_downgrade_measure.py` over **%d** graded day-cards. "
             "Detection is UNCHANGED; only the grade is recomputed. Trading set is "
             "`%s`." % (days_run, " / ".join(TRADEABLE)))
    L.append("")
    L.append("> Thresholds inside `downgrade.py` are **guesses Austin never set** — see the "
             "header there. Read the direction of these numbers, not their decimals.")
    L.append("")
    L.append("## The gate")
    L.append("")
    L.append("| grader | S-days found | day recall | false fires |")
    L.append("|---|---|---|---|")
    for label, sf, st, tf, tt, ff, ft in rows:
        L.append("| %s | **%d/%d = %.3f** | %d/%d | **%d/%d = %.3f** |"
                 % (label, sf, st, sf / max(st, 1), tf, tt, ff, ft, ff / max(ft, 1)))
    L.append("")
    L.append("Head-to-head came back **0 for 9** — every false fire the engine has today is "
             "one Austin confirmed he would not take. There is no precision credit banked, so "
             "the false-fire column is the price of the recall column.")
    L.append("")
    L.append("## Grade distribution, every signal")
    L.append("")
    L.append("| grade | count |")
    L.append("|---|---:|")
    for g in ("S", "A", "C"):
        L.append("| %s | %d (%.1f%%) |" % (g, new_grades[g], pct(new_grades[g], n_sigs)))
    L.append("")
    L.append("| downgrades tripped | signals |")
    L.append("|---:|---:|")
    for n in sorted(tripped_counts):
        L.append("| %d | %d |" % (n, tripped_counts[n]))
    L.append("")
    L.append("Confluence (+1) fired on **%d** of %d signals (%.1f%%)."
             % (confluence_hits, n_sigs, pct(confluence_hits, n_sigs)))
    L.append("")
    L.append("**Austin's own corpus is 28 S / 27 A / 3 C.** If the distribution above is "
             "nothing like that, the thresholds are wrong before anything else is.")
    L.append("")
    L.append("## The %d signals that land on one of his marked entries" % n_tp)
    L.append("")
    L.append("| grader | grades |")
    L.append("|---|---|")
    L.append("| today | %s |" % (", ".join("%s=%d" % kv for kv in tp_old.most_common()) or "-"))
    L.append("| downgrade | %s |" % (", ".join("%s=%d" % kv for kv in tp_new.most_common()) or "-"))
    L.append("")
    keep = sum(v for k, v in tp_new.items() if k in TRADEABLE)
    L.append("The old grader kept **%d** of these. The downgrade grader keeps **%d**."
             % (sum(v for k, v in tp_old.items() if k not in OLD_SKIP), keep))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote %s" % OUT)
    for label, sf, st, tf, tt, ff, ft in rows:
        print("  %-18s S %2d/%2d   day %2d/%2d   false %2d/%2d"
              % (label, sf, st, tf, tt, ff, ft))
    print("  grades: %s   confluence %d/%d"
          % (dict(new_grades), confluence_hits, n_sigs))


if __name__ == "__main__":
    main()
