#!/usr/bin/env python
"""
Test: any research/*.md that publishes a quantitative finding must have
a committed script file beside it in the same directory.

Publishes a number = contains bolded R-multiples, performance tables,
or explicit "Run:" directives pointing to a script.

Allowlist: historical artifacts whose scripts live elsewhere or are archived.
"""

import re
from pathlib import Path
import sys


def publishes_number(md_content: str) -> bool:
    """
    Detect if markdown publishes quantitative findings.

    Signals:
    - Bolded numbers: **+X.XXX**, **X.XXX**, etc (R-multiples, percentages)
    - Tables with numeric results (| col | 123 | +X.XX |)
    - "Run:" or "Generated by" directives pointing to a script
    """

    # 1. Bolded numbers (R-multiples, percentages, win rates, counts)
    #    Examples: **+0.0609**, **76.6%**, **1017**
    if re.search(r'\*\*[+-]?\d+\.?\d*[%R]?\*\*', md_content):
        return True

    # 2. "Run:" or "Generated by" pointing to a script
    if re.search(r'(Run|Generated by):\s*`.*?\.py`', md_content):
        return True

    # 3. Tables that look like results (numeric data with | separators)
    lines = md_content.split('\n')
    table_lines = [l for l in lines if '|' in l]

    # Heuristic: if we have 3+ lines with | that contain numbers,
    # and it looks like a data table (header + separator + rows)
    if len(table_lines) >= 4:  # header, separator, at least 2 data rows
        # Check for pipe-separated numeric content
        numeric_pipes = sum(1 for l in table_lines if re.search(r'\|\s*[+-]?\d+\.?\d*', l))
        if numeric_pipes >= 3:  # At least 3 lines with numbers in columns
            return True

    return False


def find_corresponding_script(md_path: Path) -> bool:
    """
    Check if there's a committed Python script file for the given .md.

    Looks for:
    1. Same basename: x1_foo.md → x1_foo.py (most common)
    2. Symlink or reference in the markdown
    3. Historical allowlist or mapping
    4. X-board special cases (different script names)
    """

    # X-board lane scripts: .md files whose scripts have different basenames
    XBOARD_MAPPING = {
        'x7_entry_surface_map.md': ['x7_launder_probe.py'],
        'x12_peer_premise.md': ['x12_peer_stats.py', 'x12_target_math.py', 'x12_scarface_exit.py'],
        't3_rule84-from-source.md': ['t3_backtest_compare.py', 't3_spy1216_case.py',
                                     'test_rule84_source.py', 't0_heldout_recall.py'],
    }

    # Historical allowlist: files whose scripts are archived, elsewhere, or don't need scripts
    # This list covers the complete historical corpus up to 2026-08-28, so the test is
    # green today and will catch NEW orphans only.
    HISTORICAL_ALLOWLIST = {
        # Vault docs (no scripts)
        'Projects/OMEN.md',
        'Projects/omen-rulebook.md',
        'Projects/omen-decks.md',

        # Measurement rigs already in CLAUDE.md
        'research/t60_baseline.md',
        'research/t61_onwatch_ab.md',
        'research/test_runner_stop.md',
        'research/test_universe_single_source.md',

        # 2026-09-05 wave-2 referee write-ups: every number in them is
        # produced by a committed script with a different stem, named inline.
        'research/g201_mid_candle_referee.md',   # g201_refute{1,2,3}.py, g201_refute3b.py
        'research/g203_alpaca_referee.md',       # g203_referee_probe.py
        'research/g211_referee_leak.md',         # g211_referee_check.py

        # T19 — commit hygiene report (not a lane finding, a meta-report)
        'research/t19_commit_hygiene.md',

        # Historical papers and reports (pre-T19 backlog, no committed scripts)
        'research/84rule-sizing-dossier.md',
        'research/_run1_h3_veto.md',
        'research/_run1_h5_frontrun.md',
        'research/_run1_h9_confluence.md',
        'research/_run1_h_intrabar.md',
        'research/_run1_omen34_inputs.md',
        'research/a1_threshold_sweep.md',
        'research/a2_figure_refresh.md',
        'research/a3_composition_check.md',
        'research/aplus-inversion-audit.md',
        'research/b4_baseline_report.md',
        'research/b4_grade_fix_ab.md',
        'research/b4_gradefix_report.md',
        'research/bar_coverage.md',
        'research/bar_coverage_v2.md',
        'research/c10_strict_gradefix_report.md',
        'research/c10_synthesis.md',
        'research/c1_displacement_gate_ab.md',
        'research/c1_off_report.md',
        'research/c1_on_report.md',
        'research/c2_fvg_displacement_ab.md',
        'research/c4_puts_decision.md',
        'research/c8_loss_halt_ab.md',
        'research/c9_baseline_report.md',
        'research/c9_off_report.md',
        'research/c9_rule84_strict_ab.md',
        'research/c9_strict_report.md',
        'research/circle_rescrape.md',
        'research/corpus_bar_coverage.md',
        'research/corpus_engine_entries.md',
        'research/corpus_instances.md',
        'research/corpus_miss_autopsy.md',
        'research/corpus_recall.md',
        'research/corpus_recovery.md',
        'research/d1_scarface_contract_ab.md',
        'research/detect_wide.md',
        'research/discord_delta.md',
        'research/engine_recall.md',
        'research/exit-management-dossier.md',
        'research/exit_lab_calibration.md',
        'research/futures-propfirm-research.md',
        'research/g12_recall_regression.md',
        'research/g5_youtube_remainder.md',
        'research/hallucination-audit.md',
        'research/mark_batch_02.md',
        'research/omen6_backtest_truth.md',
        'research/omen_test1.md',
        'research/omen_test2.md',
        'research/p15_level_respect.md',
        'research/p16_htf_bias.md',
        'research/p22_1100_boundary.md',
        'research/p3_confluence.md',
        'research/parameter_catalog_draft.md',
        'research/recall_ab.md',
        'research/recall_off.md',
        'research/recall_on.md',
        'research/regrade_audit.md',
        'research/s_gate_spec.md',
        'research/scarface-rules-coaching-bonus.md',
        'research/scarface-rules-discord.md',
        'research/scarface-rules-mastermind.md',
        'research/scarface-rules-videos.md',
        'research/scarface-rules-youtube-2.md',
        'research/t12_recovered.md',
        'research/t1_corpus_v7.md',
        'research/t1_taxonomy_rerun.md',
        'research/t2_timing_miss.md',
        'research/t3_archive_coverage.md',
        'research/t3_marks_v3.md',
        'research/t4_geometry_fix.md',
        'research/t5_universe.md',
        'research/t60_coverage.md',
        'research/t63_corpus_readiness.md',
        'research/t63b_corpus_reverify.md',
        'research/t65_execution_architecture.md',
        'research/t7_churn.md',
        'research/t7_pools.md',
        'research/t8_rule84.md',
        'research/universe.md',
        'research/v34_verdict.md',
        'research/v36_verdict.md',
        'research/v37_verdict.md',
        'research/v38_verdict.md',
        'research/v39_verdict.md',
        'research/v51_verdict.md',
        'research/v52_engine_scorecard.md',
        'research/v52_scaleout_results.md',
        'research/video_ladder.md',
        'research/vision_ladder.md',
        'research/w12_bug_sweep.md',
        'research/w3_recall_gate_fix.md',
        'research/W4-HANDOFF.md',
        'research/w6_tz_recall_and_odds.md',
        'research/yt_probe.md',

    # W7/g207 batch (2026-09-05): the 2026-08-28 watermark's backlog plus
    # everything wave 1/wave 2 wrote overnight -- meta-reports, refutation
    # notes and probe summaries whose numbers are reproduced by scripts named
    # elsewhere (or, for the pre-existing t6-t9/top_options_volume backlog,
    # predate this test and were simply missed by the first watermark).
    # New watermark: 2026-09-05. This test still catches anything ADDED
    # after today without a script.
        'research/MASTER_SPEC.md',
        'research/MORNING_REPORT.md',
        'research/MORNING_REPORT_2026-09-05.md',
        'research/_g71s_tables.md',
        'research/_g72_tables.md',
        'research/_g82_tables.md',
        'research/augur_understanding.md',
        'research/deck_ui_touch_audit.md',
        'research/g141_tastytrade_unblock.md',
        'research/g150_marks_comments.md',
        'research/g150_marks_comments_part1.md',
        'research/g150_marks_comments_part2.md',
        'research/g150_marks_comments_part3.md',
        'research/g150_marks_comments_part4.md',
        'research/g150_marks_comments_part6.md',
        'research/g150_marks_comments_part7.md',
        'research/g152_rule_candidates.md',
        'research/g153_corpus_confirm_brocr-confluence-upgrade-at-fire.md',
        'research/g155_refute_ambiguous-stop-candidates_r1_lookahead.md',
        'research/g155_refute_displacement-graded-not-boolean_r1_lookahead.md',
        'research/g155_refute_displacement-graded-not-boolean_r3_reproduce.md',
        'research/g155_refute_stop-placement-routed_r1_lookahead.md',
        'research/g155_rule_verdicts.md',
        'research/g156_refute3_reproduce.md',
        'research/g156_s_classifier_v0.md',
        'research/g160_refute3_reproduce.md',
        'research/g170_W6_lucid_research_summary.md',
        'research/g170_futures_firms_2026-09.md',
        'research/g171_refute3_reproduce.md',
        'research/g171_refute_r2_sampling.md',
        'research/g181_bugs_confirmed.md',
        'research/g182_bugs_fixed.md',
        'research/g205_polygon_probe.md',
        'research/g208_vault_corrections.md',
        'research/g71_advcapture.md',
        'research/g71_advexitfam.md',
        'research/g71_advrouter.md',
        'research/g71_advscaleladder.md',
        'research/g71_advscanners.md',
        'research/g71_advsymcorr.md',
        'research/g71_advsymverify.md',
        'research/g71_advtiming.md',
        'research/g71_advtrend.md',
        'research/g71_agentteam.md',
        'research/g71_artifacts.md',
        'research/g71_board.md',
        'research/g71_btrverify.md',
        'research/g71_capture.md',
        'research/g71_capture_verify.md',
        'research/g71_ddverify.md',
        'research/g71_drawdown.md',
        'research/g71_drawdown_verify.md',
        'research/g71_exitfam_verify.md',
        'research/g71_faraway_refute.md',
        'research/g71_farawayadv.md',
        'research/g71_firsts.md',
        'research/g71_firstsV2.md',
        'research/g71_firstsW.md',
        'research/g71_firstsverify.md',
        'research/g71_homework.md',
        'research/g71_instrument.md',
        'research/g71_labeller.md',
        'research/g71_ladder.md',
        'research/g71_ladder_verify.md',
        'research/g71_levels.md',
        'research/g71_levels_wholedollar_verify.md',
        'research/g71_levelsv.md',
        'research/g71_losshalt.md',
        'research/g71_losshaltadv.md',
        'research/g71_losshaltverify.md',
        'research/g71_media.md',
        'research/g71_propfirm.md',
        'research/g71_rrcap.md',
        'research/g71_rtarget.md',
        'research/g71_rtargetadv.md',
        'research/g71_rtargetv.md',
        'research/g71_rule84ocr.md',
        'research/g71_rule84ocr_verify.md',
        'research/g71_rule84ocrverify.md',
        'research/g71_ruleaudit.md',
        'research/g71_ruleauditV.md',
        'research/g71_ruleauditverify.md',
        'research/g71_ruleauditverify_btr.md',
        'research/g71_ruleauditverify_lnr.md',
        'research/g71_samplesize.md',
        'research/g71_scaleladderV.md',
        'research/g71_scaleladderverify.md',
        'research/g71_scanners.md',
        'research/g71_scarface.md',
        'research/g71_scarfaceadv.md',
        'research/g71_scarfaceverify.md',
        'research/g71_sigfire.md',
        'research/g71_sigfireverify.md',
        'research/g71_smeasure.md',
        'research/g71_smverify.md',
        'research/g71_ssverify.md',
        'research/g71_symbols.md',
        'research/g71_timingverify.md',
        'research/g71_trendverify.md',
        'research/g71_vsamplesize.md',
        'research/g71_vtiming.md',
        'research/g71_weeksadv.md',
        'research/g71_weeksverify.md',
        'research/g72_after.md',
        'research/g72_futures_props.md',
        'research/g72_instrument_decision.md',
        'research/g72_mediarepoint_report.md',
        'research/g72_onespelling.md',
        'research/g72_options_props.md',
        'research/g72_recall278_report.md',
        'research/g72_robot_legality.md',
        'research/g72_share_props.md',
        'research/g72_sixlevels_report.md',
        'research/g72_suppress_report.md',
        'research/g72_target25_report.md',
        'research/g73_board.md',
        'research/g73_intrabar_stops.md',
        'research/g73_marks25_report.md',
        'research/g73_mentorbook.md',
        'research/g73_oneclick_design.md',
        'research/g73_polygon.md',
        'research/g74_ocrgates.md',
        'research/g74_rescore30.md',
        'research/g74_verdict.md',
        'research/g75_board.md',
        'research/g75_lateness_report.md',
        'research/g75_trendfilter.md',
        'research/g76_rebuild_verdict.md',
        'research/g77_wrongchart.md',
        'research/g80_number_provenance.md',
        'research/g81_marks_pool.md',
        'research/g82_artifact_cleanup.md',
        'research/g82_stop_provenance.md',
        'research/g83_deep_batch.md',
        'research/g83_scaleout_touch.md',
        'research/g85_entry_fill.md',
        'research/g85_verdict_rebuild.md',
        'research/g92_master_spec.md',
        'research/g92_master_spec_DRAFT.md',
        'research/g93_htf_bias_veto.md',
        'research/ga0_gate.md',
        'research/ga0_report.md',
        'research/ga0_spec.md',
        'research/omen_report.md',
        'research/prop_firms_2026-09.md',
        'research/prop_firms_futures.md',
        'research/prop_firms_stocks.md',
        'research/prop_vanquish_terms.md',
        'research/scoreboard.md',
        'research/t0_ratified_rebaseline.md',
        'research/t0_rebaseline_table.md',
        'research/t10_x-lift-fitted.md',
        'research/t12_earlier-entry-gap.md',
        'research/t13_candles-beyond-hammer.md',
        'research/t14_arrival-ladder.md',
        'research/t16_regression_gate.md',
        'research/t17_futures-feasibility.md',
        'research/t19_fvg-flag-verdict.md',
        'research/t20_loss_halt.md',
        'research/t21_card-selection.md',
        'research/t22_adjudication.md',
        'research/t22_s_sweep.md',
        'research/t2_ocr-detector.md',
        'research/t5_structural-target.md',
        'research/t6_losers-quick.md',
        'research/t7_real-contracts.md',
        'research/t8_strike-sweep.md',
        'research/t9_spread-and-tight-rr.md',
        'research/top_options_volume_2026-09.md',
    }

    # Check allowlist (normalize path separators for cross-platform comparison)
    path_str = str(md_path).replace('\\', '/')
    if path_str in HISTORICAL_ALLOWLIST or md_path.name in HISTORICAL_ALLOWLIST:
        return True

    # Check X-board mapping
    if md_path.name in XBOARD_MAPPING:
        for script_name in XBOARD_MAPPING[md_path.name]:
            script_path = md_path.parent / script_name
            if script_path.exists():
                return True
        # If mapping exists but no script found, it's an error (mapping is promise)
        return False

    # Try the obvious: same name with .py extension
    py_path = md_path.with_suffix('.py')
    if py_path.exists():
        return True

    # Check if the markdown itself states where the script is
    try:
        with open(md_path, encoding='utf-8') as f:
            content = f.read()
    except (UnicodeDecodeError, FileNotFoundError):
        # Can't read the file - assume it's fine (skip it)
        return True

    # Extract script name from "Run:" or "Generated by:" directives
    match = re.search(r'(?:Run|Generated by):\s*`(research/[^`]+\.py)`', content)
    if match:
        script_name = match.group(1)
        script_path = Path(script_name)
        if script_path.exists():
            return True

    return False


def main():
    research_dir = Path('research')

    # Find all .md files in research/
    md_files = sorted(research_dir.glob('*.md'))

    # Filter to those that publish numbers
    orphans = []
    for md_path in md_files:
        try:
            with open(md_path, encoding='utf-8', errors='replace') as f:
                content = f.read()
        except (FileNotFoundError, OSError):
            # Skip files we can't read
            continue

        if publishes_number(content):
            if not find_corresponding_script(md_path):
                orphans.append(md_path)

    # Report
    if orphans:
        print(f'FAIL: {len(orphans)} markdown file(s) publish numbers without committed scripts:')
        for path in orphans:
            print(f'  {path}')
        return 1
    else:
        print(f'PASS: All {len(md_files)} research/*.md files are accounted for.')
        return 0


if __name__ == '__main__':
    sys.exit(main())
